import Provider from '@/util/provider'
import localFont from 'next/font/local'
import React from 'react'
import './globals.css'

const nissan = localFont({
  src: [
    {
      path: '../../public/fonts/Nissan Font/Nissan Brand Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Nissan Font/Nissan Brand Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Nissan Font/Nissan Brand Bold.otf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-nissan',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  
}: {
  children: React.ReactNode
 
}) {

  return (
    <Provider>
      <html className={`${nissan.variable} font-sans`}>
        <body>{children}</body>
      </html>
    </Provider>
  )
}
