import Footer from './components/footer'
import Header from './components/header'
import Prefooter from './components/prefooter'
import './globals.css'
import localFont from 'next/font/local'


const nissan = localFont({
  src:[
    {
      path:'../../public/fonts/Nissan Font/Nissan Brand Regular.otf',
      weight:'400',
      style:'normal'
    },
    {
      path:'../../public/fonts/Nissan Font/Nissan Brand Light.otf',
      weight:'300',
      style:'normal'
    },
    {
      path:'../../public/fonts/Nissan Font/Nissan Brand Bold.otf',
      weight:'600',
      style:'normal'
    },

  ],
  variable:'--font-nissan'
    
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${nissan.variable} font-sans`}>
      
      <body>
        <Header/>
        {children}
        <Prefooter/>
        <Footer/>
      </body>
    </html>
  )
}
